### PR TITLE
Added initial files and assests folder.

### PR DESCRIPTION
**Pull request by arensalmela**
Template for project.

### CODE REVIEW

**Review by ReindeerCode — APPROVED** [review]

**Comment by ReindeerCode** [comment]
Looks good to me!

**Review by CMDow — APPROVED** [review]
looks good to me!

**Review by ReindeerCode — APPROVED** [review]
Good work!

**Review by junkoyama — APPROVED** [review]
Looks ready to go.

**Review by ReindeerCode — APPROVED** [review]
Clicking Approve

**Review by Pregicide — APPROVED** [review]
approved

**Review by Pregicide — APPROVED** [review]
clicked files

**Review by Pregicide — APPROVED** [review]
approve

**Review by ReindeerCode — COMMENTED** [review]
Test

**Pull request merged**
